# miniconda image with conda
FROM continuumio/miniconda3

# Install basic packages
RUN apt-get update && apt-get install -y libltdl7 && rm -rf /var/lib/apt/lists/*
RUN conda update -y conda
RUN conda install -c anaconda dill networkx numpy scipy pandas seaborn matplotlib statsmodels pyyaml pytables scikit-learn
RUN conda install -c bioconda pysam
RUN conda install -c conda-forge pyvcf pypdf2 pika
#RUN conda install -c bioconda bx-python
RUN pip install azure-storage azure-batch futures azure-mgmt azure.storage.common azure.keyvault boto3 jinja2 ete3 jsonpickle bx-python
RUN apt-get update && apt-get install parallel -y && rm -rf /var/lib/apt/lists/*
# Make port 80 available to the world outside this container
EXPOSE 80

# Run python when the container launches
CMD ["python"]
