# miniconda image with conda
FROM continuumio/miniconda3

# Install basic packages
RUN apt-get update && apt-get install -y libltdl7 vim parallel && rm -rf /var/lib/apt/lists/*
RUN conda update -n base -c defaults conda setuptools
RUN conda install -c anaconda dill networkx numpy scipy pandas seaborn matplotlib statsmodels pyyaml pytables scikit-learn
RUN conda install -c bioconda pysam
RUN conda install -c conda-forge pyvcf pypdf2 pika
#RUN conda install -c bioconda bx-python
RUN pip install azure-storage azure-batch futures azure-mgmt azure.storage.common azure.keyvault==1.1.0 boto3 jinja2 ete3 jsonpickle bx-python

# Make port 80 available to the world outside this container
EXPOSE 80

# Run python on container launch
CMD ["python"]
