# build on top of out base image
FROM continuumio/miniconda

# Install any needed packages specified in requirements.txt
RUN conda install -c bioconda -c conda-forge lumpy-sv
RUN conda install -c bioconda samtools
RUN conda install -c conda-forge cryptography
# Define environment variable
#ENV NAME lumpy

# Run app.py when the container launches
CMD ["lumpy"]
