# build on top of out base image
FROM continuumio/miniconda

# Install any needed packages specified in requirements.txt
RUN conda install -c bioconda lumpy-sv
RUN conda install -c bioconda samtools
# Define environment variable
#ENV NAME lumpy

# Run app.py when the container launches
CMD ["lumpy"]
