FROM ubuntu:xenial
LABEL maintainer="Shaun Jackman <sjackman@gmail.com>"
LABEL name="Linuxbrew/xenial"
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends e2fsprogs ca-certificates curl file g++ git locales make uuid-runtime \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -f UTF-8 en_US.UTF-8 \
    && useradd -m -s /bin/bash linuxbrew \
    && echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers

RUN mkdir -p /usr/linuxbrew/bin && chmod -R 777 /usr/linuxbrew

USER linuxbrew
ENV PATH=/usr/linuxbrew/bin:$PATH

RUN git clone https://github.com/Linuxbrew/brew.git /tmp/linuxbrew/ \
    && mkdir -p /usr/linuxbrew/bin \
    && ls /tmp/*/* && cp /tmp/linuxbrew/bin/brew /usr/linuxbrew/bin/ \
    && cp -r  /tmp/linuxbrew/Library /usr/linuxbrew/Library \
    && brew config

RUN brew install brewsci/bio/biobloomtools

USER root
