# build on top of out base image
FROM shahlab.azurecr.io/scp/python_singlecell_qc:v0.0.2

# Set the working directory to /app
#WORKDIR /datadrive/singlecell/docker/app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
#RUN conda install -c dranew remixt
#RUN apt-get update && apt-get install libc-dev -y && apt-get install build-essential -y && rm -rf /var/lib/apt/lists/* && conda install -c bioconda cython
#RUN cd /app/app/remixt;python setup.py install
#RUN conda install -c conda-forge pysftp
RUN rm -rf /opt/conda/lib/python2.7/site-packages/pypeliner* /opt/conda/lib/python2.7/site-packages/single_cell*
RUN pip install git+https://github.com/shahcompbio/single_cell_pipeline.git@master
RUN pip install git+https://dgrewal@bitbucket.org/dranew/pypeliner.git@master
RUN pip install git+https://bitbucket.org/aroth85/biowrappers.git@singlecell
RUN conda install -c dranew remixt -y
# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python"]
