# build on top of out base image
FROM scdnaprod.azurecr.io/singlecellpipeline/python_singlecell_qc:v0.1.2

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN conda install -c dranew remixt && rm -rf /opt/conda/lib/python2.7/site-packages/remixt*
RUN apt-get update && apt-get install libc-dev libz-dev -y && apt-get install build-essential -y && rm -rf /var/lib/apt/lists/* && conda install -c bioconda cython
RUN pip install git+https://github.com/shahcompbio/pypeliner.git@v0.5.18
RUN pip install git+https://github.com/shahcompbio/biowrappers.git@v0.2.4
RUN pip install git+https://github.com/amcpherson/remixt.git@v0.5.11
RUN mkdir -p /root/.config/matplotlib && echo "backend : Agg" > /root/.config/matplotlib/matplotlibrc
# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME remixt

# Run app.py when the container launches
CMD ["remixt"]
