FROM continuumio/miniconda3

RUN conda install -c r r r-data.table r-tidyr r-dplyr r-r.utils r-reshape2 r-ggplot2 r-stringr r-plyr r-getopt
RUN conda install -c bioconda bioconductor-iranges bioconductor-geneplotter bioconductor-genomeinfodb 

ENV NAME r_base

CMD ["R"]
