# miniconda image with conda
FROM scdnaprod.azurecr.io/singlecellpipeline/r_base:v0.0.1

# Install basic packages
RUN conda install -c r -c conda-forge -c bioconda -c dranew -c shahcompbio bioconductor-hmmcopy-single-cell=1.12.0=r36_2 -y

# Make port 80 available to the world outside this container
EXPOSE 80

# set env name
ENV NAME hmmcopy

# Run python when the container launches
CMD ["hmmcopy_single_cell.R"]
