# build on top of out base image
FROM continuumio/miniconda3

# Install any needed packages specified in requirements.txt
RUN pip install git+https://github.com/shahcompbio/cell_cycle_classifier.git@v0.0.2
RUN pip install pandas seaborn scikit-learn
#RUN pip uninstall matplotlib -y && python -m pip install --upgrade pip && pip install matplotlib
# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME cell_cycle_classifier

# Run cell cycle on container launch
CMD ["cell_cycle_classifier"]
