# build on top of out base image
FROM scdnaprod.azurecr.io/singlecellpipeline/python_singlecell_qc:v0.1.2

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt install build-essential gcc -y && rm -rf /var/lib/apt/lists/*
RUN conda install -c bioconda -c dranew destruct==0.4.17 destruct_utils==0.4.17  -y
RUN pip install git+https://github.com/shahcompbio/pypeliner.git@v0.5.15
RUN pip install git+https://github.com/shahcompbio/biowrappers.git@v0.2.4
RUN pip install git+https://github.com/amcpherson/destruct.git@v0.4.17
RUN pip install -e git+https://github.com/amcpherson/blossomv.git#egg=blossomv
RUN pip install networkx==2.1
# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME destruct

# Run app.py when the container launches
CMD ["python"]
