FROM continuumio/miniconda

ADD . /app

RUN conda install -c anaconda openjdk
RUN cd /tmp && git clone https://github.com/UBC-Stat-ML/nowellpack.git && cd ./nowellpack/ && git checkout 83f19ba243d6916fa6dbac0bb507eca25fd8de6a && ./gradlew installDist && cp ./build/install/nowellpack/bin/* /usr/bin/ && cp ./build/install/nowellpack/lib/* /usr/lib/
#RUN conda install -c conda-forge r r-data.table r-tidyr r-optparse r-dplyr r-r.utils r-reshape2 r-ggplot2 r-stringr
#RUN cp /app/scripts/* /usr/bin/
RUN apt-get update && apt-get install xvfb -y
# libxtst6 -y
EXPOSE 80
ENV NAME corrupt-tree
