# build on top of out base image
FROM shahlab.azurecr.io/scp/python_singlecell_qc:v0.0.5

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN conda install -c bioconda -c dranew destruct blossomv -y
RUN rm -rf /opt/conda/lib/python2.7/site-packages/pypeliner* /opt/conda/lib/python2.7/site-packages/destruct*
RUN pip install git+https://github.com/shahcompbio/single_cell_pipeline.git@master
RUN pip install git+https://github.com/shahcompbio/pypeliner.git@master
RUN pip install git+https://bitbucket.org/aroth85/biowrappers.git@singlecell
RUN pip install git+https://github.com/amcpherson/destruct.git@master
# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME destruct

# Run app.py when the container launches
CMD ["python"]
