# miniconda image with conda
FROM continuumio/miniconda

ADD . /app

# Install basic packages
RUN apt-get update && apt-get install -y libltdl7 && apt-get install libgfortran3 -y && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y software-properties-common gnupg && add-apt-repository -y ppa:neurobin/ppa && apt-get install -y shc
RUN conda update -y conda
RUN conda install -c r r-plyr r-getopt r-data.table
RUN conda install -c bioconda bioconductor-hmmcopy
RUN conda install -c dranew hmmcopy_utils
RUN cp /app/hmmcopy.R /usr/bin/hmmcopy.R && chmod 777 /usr/bin/hmmcopy.R
RUN echo '#!/bin/bash' > /usr/bin/hmmcopy;echo "Rscript /usr/bin/hmmcopy.R \$*" >> /usr/bin/hmmcopy && chmod u+x /usr/bin/hmmcopy
# Make port 80 available to the world outside this container
EXPOSE 80

# set env name
ENV NAME hmmcopy
# Run python when the container launches
CMD ["hmmcopy"]
