# build on top of out base image
FROM shahlab.azurecr.io/scp/python_singlecell_qc:v0.0.4

# Set the working directory to /app
#WORKDIR /datadrive/singlecell/docker/app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN conda install -c bioconda trim-galore
# Make port 80 available to the world outside this container
#EXPOSE 80

# Define environment variable
#ENV NAME World

# Run app.py when the container launches
CMD ["python"]
